//SET UP
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE my_db;

CREATE OR REPLACE SCHEMA my_schema;

//CREATING TABLE
CREATE OR REPLACE TABLE task_table
(
ID INT,
NAME STRING()
)

//INSERTING DATA
INSERT INTO task_table (ID,NAME) VALUES
(1, 'Brian'),
(2, 'Muriiki'),
(3, 'Jane');

//QUERYING DATA
SELECT *
FROM task_table

//CREATING TASKS
CREATE OR REPLACE TASK my_task
WAREHOUSE = COMPUTE_WH
SCHEDULE= '1 MINUTE'
AS 
INSERT INTO task_table (ID,NAME) VALUES
(1, 'Brian'),
(2, 'Muriiki'),
(3, 'Jane');

//VIEWING TASKS
SHOW TASKS;

ALTER TASK my_task RESUME;

ALTER TASK my_task SUSPEND;
