//SET UP
USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE my_db;

CREATE OR REPLACE SCHEMA my_schema;

//CREATING TABLE
CREATE OR REPLACE TABLE time_travel
(
ID INT,
NAME STRING()
)

//INSERTING DATA
INSERT INTO time_travel (ID,NAME) VALUES
(1, 'Brian'),
(2, 'Muriiki'),
(3, 'Jane');

//QUERYING DATA
SELECT *
FROM time_travel

DELETE FROM time_travel WHERE ID=3

SELECT *
FROM time_travel AT(OFFSET => -60*5);
